cache: apt
dist: trusty
sudo: false
language: python
cache:
  pip: true
  directories:
  - $HOME/virtualenv
python:
  - "3.6"
install:
  - pip install ucca
env:
  matrix:
  - DATASET=00/ucca
script:
  - scripts/insert_tokens.sh
  - python -m scripts.validate $DATASET

