cache: apt
dist: trusty
sudo: false
language: python
cache:
  pip: true
  directories:
  - $HOME/virtualenv
python:
  - "3.6"
install:
  - pip install ucca
script:
  - scripts/insert_tokens.sh || travis_terminate 1
  - python -m scripts.validate xml

